import streamlit as st
import pandas as pd
from datetime import datetime, timedelta


_SEVERITY_COLORS = {
    "CRITICAL": "🔴",
    "HIGH": "🟠",
    "MEDIUM": "🟡",
    "LOW": "🟢",
    "INFO": "🔵",
}


def render(client):
    st.title("🚨 Alerts")

    # ── Controls ───────────────────────────────────────
    col1, col2 = st.columns([1, 3])
    with col1:
        hours = st.selectbox(
            "Time range",
            [1, 6, 12, 24, 48, 72],
            index=3,
            format_func=lambda h: f"Last {h}h",
        )
    with col2:
        limit = st.slider("Max alerts", 10, 500, 100, key="alert_limit")

    since = (datetime.utcnow() - timedelta(hours=hours)).isoformat() + "Z"

    # ── Fetch alerts ───────────────────────────────────
    try:
        alerts = client.get_alerts(limit=limit, since=since)
    except Exception as e:
        st.error(f"Failed to load alerts: {e}")
        return

    if not alerts:
        st.info(
            "No alerts in the selected time range. "
            "Alerts are generated by the detection engine when rules match."
        )
        return

    st.caption(f"Showing {len(alerts)} alert(s)")

    # ── Build dataframe ────────────────────────────────
    alerts_df = pd.DataFrame(alerts)

    display_cols = [
        col
        for col in [
            "timestamp",
            "rule_id",
            "severity",
            "confidence",
            "actor",
            "ip",
            "service_name",
        ]
        if col in alerts_df.columns
    ]

    if display_cols:
        display_df = alerts_df[display_cols].copy()

        if "confidence" in display_df.columns:
            display_df["confidence"] = display_df["confidence"].apply(
                lambda x: f"{x * 100:.0f}%"
                if isinstance(x, (int, float))
                else x
            )
        if "severity" in display_df.columns:
            display_df["severity"] = display_df["severity"].apply(
                lambda x: f"{_SEVERITY_COLORS.get(x, '')} {x}" if x else x
            )
        if "timestamp" in display_df.columns:
            display_df["timestamp"] = display_df["timestamp"].apply(
                lambda x: x[:19].replace("T", " ")
                if isinstance(x, str)
                else x
            )

        st.dataframe(
            display_df, use_container_width=True, hide_index=True
        )
    else:
        st.dataframe(alerts_df, use_container_width=True, hide_index=True)

    # ── Alert detail ───────────────────────────────────
    st.divider()
    st.subheader("Alert Detail")

    if "detection_id" in alerts_df.columns and len(alerts_df) > 0:
        selected = st.selectbox(
            "Select an alert to inspect",
            options=alerts_df["detection_id"].tolist(),
            format_func=lambda x: f"{x[:16]}…"
            if isinstance(x, str) and len(x) > 16
            else str(x),
        )
        if selected:
            detail = (
                alerts_df[alerts_df["detection_id"] == selected]
                .iloc[0]
                .to_dict()
            )
            st.json(detail)
    else:
        st.info("Select an alert above to see its full payload.")
